# Built with arch: amd64 flavor: lxde image: ubuntu:20.04
#
################################################################################
# base system
################################################################################


#FROM ubuntu:20.04 as system
#FROM ros:foxy-ros-base as system
#FROM ros:galactic-ros-base as system
FROM rosmed/docker-ubuntu-vnc-desktop-slicer:ismr2023 as system

#
# Build SlicerROS2
#
WORKDIR /root
